---
language: ruby

bundler_args: --without system_tests development

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec strings:generate readme'

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4"
  - rvm: 2.4.3
    env: PUPPET_GEM_VERSION="~> 5"
  - rvm: 2.4.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-6"
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.3
    sudo: required
    services: docker
    env: BEAKER_set="centos-7"
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.3
    sudo: required
    services: docker
    env: BEAKER_set="debian-8"
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.3
    sudo: required
    services: docker
    env: BEAKER_set="debian-9"
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.3
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1404"
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.3
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-1604"
    bundler_args:
    script: bundle exec rake beaker
# TODO: uncomment when puppet supports ubuntu 18.04 bionic. The file at this
# URL will exist when this is ready
# http://apt.puppetlabs.com/puppet5-release-bionic.deb
#  - rvm: 2.4.3
#    sudo: required
#    services: docker
#    env: BEAKER_set="ubuntu-1804"
#    bundler_args:
#    script: bundle exec rake beaker

notifications:
  email: false
